import { createApiClient } from './client'
import { getApiBaseUrl } from './baseUrl'
const client = createApiClient(getApiBaseUrl('/tools'))
const recommendClient = createApiClient(getApiBaseUrl('/recommend'))
export const getPresetTools = (category) => client.get('/presets', { params: category ? { category } : {} })
export const getRecommendedTools = (category, subject, needType) => recommendClient.post('/', { category, subject, need_type: needType, step: 3 })
export const getTool = (id) => client.get(`/id/${id}`)
export const getSharedTool = (shareCode) => client.get(`/share/${shareCode}`)
export const getMyTools = (params = {}) => client.get('/mine/list', { params })
export const getTemplates = () => client.get('/templates/list')
export const createTool = (payload) => client.post('/', payload)
export const updateTool = (id, payload) => client.put(`/${id}`, payload)
export const deleteTool = (id) => client.delete(`/${id}`)
export const restoreTool = (id) => client.post(`/${id}/restore`)
export const copyPresetTool = (id) => client.post(`/presets/${id}/copy`)
export const getShareLink = (id) => client.get(`/${id}/share`)
export const updateShareSettings = (id, payload) => client.put(`/${id}/share`, payload)
export const revokeShare = (id) => client.post(`/${id}/share/revoke`)
